### ISSUE TITLE
Error on activation

### ISSUE THREAD

**Issue by webangon** [Giuseppe-Mazzapica/ATP#3]
Hi 
Thank for this plugin but I have got this error while activating 

The plugin generated 2139 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

Any idea?

**Comment by Giuseppe-Mazzapica** [comment]
@webangon Are you sure that your current setup meets [ATP requirements](https://github.com/Giuseppe-Mazzapica/ATP#requirements)?

More specifically, are you sure that your sistem has PHP 5.4+?

**Comment by webangon** [comment]
I am using php 5.5.12 wamp server. But I do not have composer installed .wordpress 4.1

**Comment by Giuseppe-Mazzapica** [comment]
@webangon ATP **requires** Composer to be installed.

Download the plugin zip and activate it is not a way to go, because the plugin relies on Composer autoload to work.

To use Composer you can just:

1. download `composer.phar` file from [here](http://getcomposer.org/composer.phar) and put in your WordPress plugin folder. **No** installation or configuration required.

2. `cd` to plugin folder from console (if you use Windows, hold SHIFT while right-click on plugins folder in explorer, then click "Open command prompt here...")

3. Type (or copy&paste) installation command you find in [README](https://github.com/Giuseppe-Mazzapica/ATP#installation)

It tooks no more than 1 minute and it's super-easy.

You need to do that only in your local server. Online you have only to publish the plugin folder with anything inside it (you'll notice a `vendor` folder created by Composer).

**Comment by webangon** [comment]
Thank you
